# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0

  resources:
    - resource: PowerShellGet/PSModule
      id: PsIni
      directives:
        description: Install PsIni module from PSGallery
        allowPrerelease: true
      settings:
        Name: PsIni
        Repository: PSGallery
        Ensure: Present
